# Site Settings
title: Hack the Burgh
email: htb@comp-soc.com	
description: "Major League Hacking hits Edinburgh"
baseurl: ""
url: "http://hacktheburgh.com"
author: "CompSoc"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Schedule
   url: "#schedule"
 - text: About
   url: "#about"
 - text: FAQ
   url: "#faq"
 - text: "Sponsors"
   url: "#sponsors"
# - text: Twitter Wall
#   url: "/wall"
 - text: Where is HTB?
   url: "#map"
# - text: "Mailing List"
#   url: "https://ti.to/hacktheburgh/htb2015"

permalink: pretty
